apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux.yaml
images:
- name: docker.io/fluxcd/flux
  newName: acraksxc5oxbw43eq7o.azurecr.io/fluxcd/flux
- name: docker.io/library/memcached
  newName: acraksxc5oxbw43eq7o.azurecr.io/library/memcached